
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Plugins.mod.io.Runtime.ModIO.Implementation.Classes;

namespace ModIO.Implementation.API.Requests
{
    internal static class EndAnalyticsSession
    {
        public static WebRequestConfig Request(string sessionId)
        {
            var request = new WebRequestConfig()
            {
                Url = $"{Settings.server.serverURL}{@"/metrics/sessions/end"}",
                RequestMethodType = "POST",
            };

            var sessionOrderId = AnalyticsManager.IncreaseSessionOrderId(sessionId);
            var sessionData = AnalyticsManager.GetSession(sessionId);
            var nonce = Guid.NewGuid().ToString();
            var sessionTs = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds().ToString();
            
            Dictionary<string, string> kvps = new Dictionary<string, string>
            {
                {
                    "session_id", sessionId
                }, //Client provided and used in session start request previously,
                {
                    "session_ts", sessionTs
                }, //milliseconds since UNIX generated by client
                {
                    "session_hash", sessionData.GetSessionHash(false, sessionTs, nonce)
                }, //HMAC_SHA256(secret-key, session-ts + session_id + session_nonce)
                {
                    "session_nonce", nonce
                }, //unique nonce
                {
                    "session_order_id", sessionOrderId.ToString()
                }, //The next number after the last submitted heartbeat
            };
            request.RawBodyData = JsonConvert.SerializeObject(kvps);

            return request;
        }
    }
}
