using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Plugins.mod.io.Runtime.ModIO.Implementation.Classes;

namespace ModIO.Implementation.API.Requests
{
    internal static class StartAnalyticsSession
    {
        public static WebRequestConfig Request(string sessionId, long[] modIds)
        {
            var request = new WebRequestConfig()
            {
                //https://{game-id}.modapi.io/v1/metrics/sessions/start
                Url = $"{Settings.server.serverURL}{@"/metrics/sessions/start"}",
                RequestMethodType = "POST"
            };
            
            AnalyticsManager.AddSession(sessionId, modIds);
            var sessionData = AnalyticsManager.GetSession(sessionId);
            string[] ids = modIds.Select(id => id.ToString()).ToArray();
            var nonce = Guid.NewGuid().ToString();
            var sessionTs = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds().ToString();
            
            Dictionary<string, object> jsonKvps = new Dictionary<string, object>
            {
                {
                    "session_id", sessionId
                }, //Provided by the client and must be unique (guid)
                {
                    "ids", ids
                },
                {
                    "session_ts", sessionTs
                }, //milliseconds since UNIX
                {
                    "session_hash", sessionData.GetSessionHash(true, sessionTs, nonce)
                }, //HMAC_SHA256(secret-key, ids + session-ts + session_id + session_nonce)
                {
                    "session_nonce", nonce
                }, //unique nonce generated by integration
                {
                    "session_order_id", "1"
                }, //all start requests begin at 1
            };
            request.RawBodyData = JsonConvert.SerializeObject(jsonKvps);

            return request;
        }
    }
}
